blank_issues_enabled: false
contact_links:
  - name: My Portfolio
    url: https://mindulle.github.io/
    about: ðŸŽ‰ Welecome to my world!
  - name: My Blog
    url: https://mindulle.github.io/blog
    about: ðŸ“š my peaceful story.
